import dotenv from "dotenv";
import { z } from "zod";

dotenv.config();

const schema = z.object({
  NODE_ENV: z.string().default("development"),
  ASCEND_APP_ENV: z.enum(["local", "staging", "production"]).default("local"),
  ASCEND_BILLING_CHANNEL: z.enum(["web_stripe", "google_play", "disabled"]).default("web_stripe"),
  ASCEND_PRODUCTION_DATABASE_URL_SHA256: z.string().regex(/^[a-f0-9]{64}$/i).optional(),
  ASCEND_PRODUCTION_R2_BUCKET: z.string().optional(),
  ANALYTICS_ENVIRONMENT: z.enum(["local", "staging", "production"]).default("local"),
  MONITORING_ENVIRONMENT: z.enum(["local", "staging", "production"]).default("local"),
  SCHEDULED_JOBS_ENABLED: z.string().default("false").transform((value) => value.toLowerCase() === "true"),
  EMAIL_DELIVERY_MODE: z.enum(["disabled", "capture", "live"]).default("disabled"),
  PUSH_DELIVERY_MODE: z.enum(["disabled", "capture", "live"]).default("disabled"),
  PORT: z.coerce.number().default(4000),
  DATABASE_URL: z.string().min(1),
  DB_POOL_MAX: z.coerce.number().int().min(1).max(100).default(10),
  DB_CONNECTION_TIMEOUT_MS: z.coerce.number().int().min(500).max(60_000).default(5_000),
  DB_IDLE_TIMEOUT_MS: z.coerce.number().int().min(1_000).max(300_000).default(30_000),
  DB_STATEMENT_TIMEOUT_MS: z.coerce.number().int().min(1_000).max(120_000).default(30_000),
  CORS_ORIGIN: z.string().default("http://localhost:3000"),
  FIREBASE_PROJECT_ID: z.string().optional(),
  FIREBASE_CLIENT_EMAIL: z.string().optional(),
  FIREBASE_PRIVATE_KEY: z.string().optional(),
  BOOTSTRAP_OWNER_EMAIL: z.string().optional(),
  CRON_SECRET: z.string().optional(),
  AWS_REGION: z.string().default("ap-southeast-1"),
  AWS_S3_ENDPOINT: z.string().optional(),
  AWS_ACCESS_KEY_ID: z.string().optional(),
  AWS_SECRET_ACCESS_KEY: z.string().optional(),
  AWS_S3_BUCKET: z.string().optional(),
  AI_PROVIDER: z.enum(["openai", "gemini", "kimi", "qwen", "local"]).default("openai"),
  OPENAI_API_KEY: z.string().optional(),
  OPENAI_MODEL: z.string().default("gpt-4.1-mini"),
  GEMINI_API_KEY: z.string().optional(),
  GEMINI_MODEL: z.string().default("gemini-2.5-flash"),
  AI_MONTHLY_SPEND_LIMIT_CENTS: z.coerce.number().int().positive().default(5000),
  AI_MONTHLY_FOOD_ANALYSIS_LIMIT: z.coerce.number().int().positive().default(1000),
  AI_MONTHLY_CHAT_LIMIT: z.coerce.number().int().positive().default(3000),
  AI_MONTHLY_WEEKLY_REPORT_LIMIT: z.coerce.number().int().positive().default(500),
  AI_FOOD_ANALYSIS_ESTIMATED_COST_CENTS: z.coerce.number().nonnegative().default(2),
  AI_CHAT_ESTIMATED_COST_CENTS: z.coerce.number().nonnegative().default(1),
  AI_WEEKLY_REPORT_ESTIMATED_COST_CENTS: z.coerce.number().nonnegative().default(2),
  FOOD_AI_PERFORMANCE_LOGS: z.string().default("false").transform((value) => value.toLowerCase() === "true"),
  BODY_COMPOSITION_AI_DEBUG_LOGS: z.string().default("false").transform((value) => value.toLowerCase() === "true"),
  FOOD_AI_REMOTE_IMAGE_HOSTS: z.string().default(""),
  PAYMENT_PROVIDER: z.enum(["stripe", "lemonsqueezy", "toyyibpay"]).default("stripe"),
  FRONTEND_URL: z.string().default("http://localhost:3000"),
  STRIPE_SECRET_KEY: z.string().optional(),
  STRIPE_WEBHOOK_SECRET: z.string().optional(),
  STRIPE_PREMIUM_PRICE_ID: z.string().optional(),
  STRIPE_TRAINER_PRO_PRICE_ID: z.string().optional(),
  GOOGLE_PLAY_PACKAGE_NAME: z.string().optional(),
  GOOGLE_PLAY_SERVICE_ACCOUNT_EMAIL: z.string().optional(),
  GOOGLE_PLAY_SERVICE_ACCOUNT_PRIVATE_KEY: z.string().optional(),
  GOOGLE_PLAY_BILLING_ENABLED: z.string().default("false").transform((value) => value.toLowerCase() === "true"),
  GOOGLE_PLAY_TOKEN_ENCRYPTION_KEY: z.string().optional(),
  GOOGLE_PLAY_TOKEN_KEY_VERSION: z.coerce.number().int().positive().default(1),
  GOOGLE_PLAY_ACCOUNT_OBFUSCATION_SECRET: z.string().optional(),
  GOOGLE_PLAY_RTDN_ENABLED: z.string().default("false").transform((value) => value.toLowerCase() === "true"),
  GOOGLE_PLAY_RTDN_AUDIENCE: z.string().optional(),
  GOOGLE_PLAY_RTDN_SERVICE_ACCOUNT_EMAIL: z.string().optional(),
  GOOGLE_PLAY_ENTITLEMENT_FRESHNESS_HOURS: z.coerce.number().int().min(1).max(168).default(24),
  GOOGLE_PLAY_PREMIUM_MONTHLY_PRODUCT_ID: z.string().default("ascend_premium_monthly"),
  GOOGLE_PLAY_PREMIUM_YEARLY_PRODUCT_ID: z.string().default("ascend_premium_yearly"),
  GOOGLE_PLAY_PREMIUM_MONTHLY_BASE_PLAN_ID: z.string().default("monthly"),
  GOOGLE_PLAY_PREMIUM_YEARLY_BASE_PLAN_ID: z.string().default("yearly"),
  GOOGLE_PLAY_PREMIUM_MONTHLY_PRICE_CENTS: z.coerce.number().int().positive().default(1999),
  GOOGLE_PLAY_PREMIUM_YEARLY_PRICE_CENTS: z.coerce.number().int().positive().default(19999),
  ATHLETE_MODE_ENABLED: z.string().default("true").transform((value) => value.toLowerCase() !== "false"),
  LEMONSQUEEZY_API_BASE_URL: z.string().default("https://api.lemonsqueezy.com/v1"),
  LEMONSQUEEZY_API_KEY: z.string().optional(),
  LEMONSQUEEZY_STORE_ID: z.string().optional(),
  LEMONSQUEEZY_PREMIUM_VARIANT_ID: z.string().optional(),
  LEMONSQUEEZY_TRAINER_PRO_VARIANT_ID: z.string().optional(),
  LEMONSQUEEZY_WEBHOOK_SECRET: z.string().optional(),
  TOYYIBPAY_BASE_URL: z.string().default("https://toyyibpay.com"),
  TOYYIBPAY_SECRET_KEY: z.string().optional(),
  TOYYIBPAY_CATEGORY_CODE: z.string().optional(),
  TOYYIBPAY_RETURN_URL: z.string().optional(),
  TOYYIBPAY_CALLBACK_URL: z.string().optional(),
  GMAIL_CLIENT_ID: z.string().optional(),
  GMAIL_CLIENT_SECRET: z.string().optional(),
  GMAIL_REDIRECT_URI: z.string().optional(),
  GMAIL_TOKEN_ENCRYPTION_KEY: z.string().optional(),
  TRAINER_HOMEWORK_V1: z.string().default("false").transform((value) => value.toLowerCase() === "true"),
  WORKOUT_CAPTURE_V1: z.string().default("false").transform((value) => value.toLowerCase() === "true"),
  WORKOUT_PROGRESSION_INTELLIGENCE_V1: z.string().default("false").transform((value) => value.toLowerCase() === "true"),
  WORKOUT_PROGRESSION_INTELLIGENCE_V3: z.string().default("false").transform((value) => value.toLowerCase() === "true"),
  TRAINER_SESSION_CAPTURE_V1: z.string().default("false").transform((value) => value.toLowerCase() === "true"),
  MOMENTUM_V2: z.string().default("true").transform((value) => value.toLowerCase() !== "false")
});

export const env = schema.parse(process.env);
